export const AUTHORIZATION_ROUTE = '/auth'
export const USERS_ROUTE = '/users'
export const PAYMENTS_ROUTE = '/payments'
export const PROFILE_ROUTE = '/profile'
export const NEW_USER_ROUTE = '/new_user'
export const NEW_ADMIN_ROUTE = '/new_admin'